package app.fqrs.tglive.utils

data class Country(
    val name: String,
    val code: String,
    val dialCode: String,
    val flag: String
)

object CountryHelper {
    
    fun getCountries(): List<Country> = listOf(
        Country("India", "IN", "+91", "🇮🇳"),
        Country("United States", "US", "+1", "🇺🇸"),
        Country("United Kingdom", "GB", "+44", "🇬🇧"),
        Country("Canada", "CA", "+1", "🇨🇦"),
        Country("Australia", "AU", "+61", "🇦🇺"),
        Country("Germany", "DE", "+49", "🇩🇪"),
        Country("France", "FR", "+33", "🇫🇷"),
        Country("Italy", "IT", "+39", "🇮🇹"),
        Country("Spain", "ES", "+34", "🇪🇸"),
        Country("Netherlands", "NL", "+31", "🇳🇱"),
        Country("Belgium", "BE", "+32", "🇧🇪"),
        Country("Switzerland", "CH", "+41", "🇨🇭"),
        Country("Austria", "AT", "+43", "🇦🇹"),
        Country("Sweden", "SE", "+46", "🇸🇪"),
        Country("Norway", "NO", "+47", "🇳🇴"),
        Country("Denmark", "DK", "+45", "🇩🇰"),
        Country("Finland", "FI", "+358", "🇫🇮"),
        Country("Poland", "PL", "+48", "🇵🇱"),
        Country("Czech Republic", "CZ", "+420", "🇨🇿"),
        Country("Hungary", "HU", "+36", "🇭🇺"),
        Country("Romania", "RO", "+40", "🇷🇴"),
        Country("Bulgaria", "BG", "+359", "🇧🇬"),
        Country("Greece", "GR", "+30", "🇬🇷"),
        Country("Turkey", "TR", "+90", "🇹🇷"),
        Country("Russia", "RU", "+7", "🇷🇺"),
        Country("Ukraine", "UA", "+380", "🇺🇦"),
        Country("Belarus", "BY", "+375", "🇧🇾"),
        Country("Lithuania", "LT", "+370", "🇱🇹"),
        Country("Latvia", "LV", "+371", "🇱🇻"),
        Country("Estonia", "EE", "+372", "🇪🇪"),
        Country("China", "CN", "+86", "🇨🇳"),
        Country("Japan", "JP", "+81", "🇯🇵"),
        Country("South Korea", "KR", "+82", "🇰🇷"),
        Country("Singapore", "SG", "+65", "🇸🇬"),
        Country("Malaysia", "MY", "+60", "🇲🇾"),
        Country("Thailand", "TH", "+66", "🇹🇭"),
        Country("Indonesia", "ID", "+62", "🇮🇩"),
        Country("Philippines", "PH", "+63", "🇵🇭"),
        Country("Vietnam", "VN", "+84", "🇻🇳"),
        Country("Pakistan", "PK", "+92", "🇵🇰"),
        Country("Bangladesh", "BD", "+880", "🇧🇩"),
        Country("Sri Lanka", "LK", "+94", "🇱🇰"),
        Country("Nepal", "NP", "+977", "🇳🇵"),
        Country("Bhutan", "BT", "+975", "🇧🇹"),
        Country("Maldives", "MV", "+960", "🇲🇻"),
        Country("Afghanistan", "AF", "+93", "🇦🇫"),
        Country("Iran", "IR", "+98", "🇮🇷"),
        Country("Iraq", "IQ", "+964", "🇮🇶"),
        Country("Israel", "IL", "+972", "🇮🇱"),
        Country("Jordan", "JO", "+962", "🇯🇴"),
        Country("Lebanon", "LB", "+961", "🇱🇧"),
        Country("Syria", "SY", "+963", "🇸🇾"),
        Country("Saudi Arabia", "SA", "+966", "🇸🇦"),
        Country("UAE", "AE", "+971", "🇦🇪"),
        Country("Qatar", "QA", "+974", "🇶🇦"),
        Country("Kuwait", "KW", "+965", "🇰🇼"),
        Country("Bahrain", "BH", "+973", "🇧🇭"),
        Country("Oman", "OM", "+968", "🇴🇲"),
        Country("Yemen", "YE", "+967", "🇾🇪"),
        Country("Egypt", "EG", "+20", "🇪🇬"),
        Country("Libya", "LY", "+218", "🇱🇾"),
        Country("Tunisia", "TN", "+216", "🇹🇳"),
        Country("Algeria", "DZ", "+213", "🇩🇿"),
        Country("Morocco", "MA", "+212", "🇲🇦"),
        Country("Sudan", "SD", "+249", "🇸🇩"),
        Country("South Africa", "ZA", "+27", "🇿🇦"),
        Country("Nigeria", "NG", "+234", "🇳🇬"),
        Country("Kenya", "KE", "+254", "🇰🇪"),
        Country("Ghana", "GH", "+233", "🇬🇭"),
        Country("Ethiopia", "ET", "+251", "🇪🇹"),
        Country("Tanzania", "TZ", "+255", "🇹🇿"),
        Country("Uganda", "UG", "+256", "🇺🇬"),
        Country("Rwanda", "RW", "+250", "🇷🇼"),
        Country("Zambia", "ZM", "+260", "🇿🇲"),
        Country("Zimbabwe", "ZW", "+263", "🇿🇼"),
        Country("Botswana", "BW", "+267", "🇧🇼"),
        Country("Namibia", "NA", "+264", "🇳🇦"),
        Country("Brazil", "BR", "+55", "🇧🇷"),
        Country("Argentina", "AR", "+54", "🇦🇷"),
        Country("Chile", "CL", "+56", "🇨🇱"),
        Country("Colombia", "CO", "+57", "🇨🇴"),
        Country("Peru", "PE", "+51", "🇵🇪"),
        Country("Venezuela", "VE", "+58", "🇻🇪"),
        Country("Ecuador", "EC", "+593", "🇪🇨"),
        Country("Bolivia", "BO", "+591", "🇧🇴"),
        Country("Paraguay", "PY", "+595", "🇵🇾"),
        Country("Uruguay", "UY", "+598", "🇺🇾"),
        Country("Mexico", "MX", "+52", "🇲🇽"),
        Country("Guatemala", "GT", "+502", "🇬🇹"),
        Country("Costa Rica", "CR", "+506", "🇨🇷"),
        Country("Panama", "PA", "+507", "🇵🇦"),
        Country("Nicaragua", "NI", "+505", "🇳🇮"),
        Country("Honduras", "HN", "+504", "🇭🇳"),
        Country("El Salvador", "SV", "+503", "🇸🇻"),
        Country("Belize", "BZ", "+501", "🇧🇿"),
        Country("Jamaica", "JM", "+1876", "🇯🇲"),
        Country("Cuba", "CU", "+53", "🇨🇺"),
        Country("Dominican Republic", "DO", "+1809", "🇩🇴"),
        Country("Haiti", "HT", "+509", "🇭🇹"),
        Country("Puerto Rico", "PR", "+1787", "🇵🇷"),
        Country("Trinidad and Tobago", "TT", "+1868", "🇹🇹")
    )
    
    fun getDefaultCountry(): Country = getCountries().first { it.code == "IN" }
    
    fun getCountryByCode(code: String): Country? = getCountries().find { it.code == code }
    
    fun getCountryByDialCode(dialCode: String): Country? = getCountries().find { it.dialCode == dialCode }
}